Docs Refactoring
canonical/content-cache-k8s-operator pull request #23
Opened 2023-03-23 19:03 UTC by gtrkiller

This PR aims to refactor the docs according to the Documentation Team's defined criteria.

2023-03-23 20:16 UTC, merkata submitted a review, later dismissed

2023-03-23 23:29 UTC, jdkandersson approved these changes

2023-03-24 01:46 UTC, yanksyoon approved these changes
LGTM

2023-03-24 09:02 UTC, arturo-seijas commented on docs/how-to/cache-content-with-openstack-swift.md
> +# Cache content with openstack/swift storage
Same here
s/openstack/swift/OpenStack/Swift

2023-03-24 09:03 UTC, arturo-seijas commented on docs/tutorial/getting-started.md
> +### Relate to ingress by using nginx ingress integrator
Same here
s/nginx/NGINX

2023-03-24 09:19 UTC, arturo-seijas requested changes
Left some comments inline

2023-03-27 15:55 UTC, arturo-seijas approved these changes
LGTM

2023-03-28 02:08 UTC, jdkandersson approved these changes

2023-03-28 12:04 UTC, merged